version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker run -d --name db westsoft/proprietary-db:1.2.3

     # build the application image
     - run: docker build -t westsoft/app:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push westsoft/app:$CIRCLE_BRANCH
